# Generated by Django 4.2.11 on 2026-04-17 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(verbose_name='เวลาออกเดินทาง')),
                ('arrival_time', models.TimeField(verbose_name='เวลาถึงโดยประมาณ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคาตั๋ว (บาท)')),
                ('bus_type', models.CharField(default='รถบัสปรับอากาศ VIP', max_length=50, verbose_name='ประเภทรถ')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.route', verbose_name='เส้นทาง')),
            ],
            options={
                'verbose_name': 'รอบรถ',
                'verbose_name_plural': 'รอบรถทั้งหมด',
                'db_table': 'SouthernTour_Schedules',
            },
        ),
    ]
